info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Go NBXplorer API
  title: Go NBXplorer API
  version: "1.0"
paths: {}
swagger: "2.0"
